// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQNyA8FEDpneg5OhenAokJD6hQ9kNQo0',
    appId: '1:1031951152619:web:d63cec2b1b891d3eb995ae',
    messagingSenderId: '1031951152619',
    projectId: 'clean-architecture-9e82d',
    authDomain: 'clean-architecture-9e82d.firebaseapp.com',
    storageBucket: 'clean-architecture-9e82d.appspot.com',
    measurementId: 'G-HVSFMS9TL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUhplxRbqUpr3bwRzuYvOHbog924a-0Hs',
    appId: '1:1031951152619:android:1190867c92563b4fb995ae',
    messagingSenderId: '1031951152619',
    projectId: 'clean-architecture-9e82d',
    storageBucket: 'clean-architecture-9e82d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByw5W-2zOOcWqLqKUIK-0OBYnlYjL-85k',
    appId: '1:1031951152619:ios:152c4a5cdb69be88b995ae',
    messagingSenderId: '1031951152619',
    projectId: 'clean-architecture-9e82d',
    storageBucket: 'clean-architecture-9e82d.appspot.com',
    iosBundleId: 'com.example.flutterCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByw5W-2zOOcWqLqKUIK-0OBYnlYjL-85k',
    appId: '1:1031951152619:ios:152c4a5cdb69be88b995ae',
    messagingSenderId: '1031951152619',
    projectId: 'clean-architecture-9e82d',
    storageBucket: 'clean-architecture-9e82d.appspot.com',
    iosBundleId: 'com.example.flutterCleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtQNyA8FEDpneg5OhenAokJD6hQ9kNQo0',
    appId: '1:1031951152619:web:03a5fa1da8e3eb0cb995ae',
    messagingSenderId: '1031951152619',
    projectId: 'clean-architecture-9e82d',
    authDomain: 'clean-architecture-9e82d.firebaseapp.com',
    storageBucket: 'clean-architecture-9e82d.appspot.com',
    measurementId: 'G-EQNS0EXT5X',
  );
}
